name: Create Issue
description: Create an issue to ship.
projects: ['rossgalloway/3']
body:
  - type: markdown
    attributes:
      value: |
        ### What type of issue is this?
  - type: dropdown
    id: type
    attributes:
      label: What type of issue is this?
      options:
        - Bug
        - Minor Change
        - Major Change
        - Feature
        - Prep
        - Wishlist
      default: 0
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: What needs to be shipped?
      description: Describe what needs to be improved or what feature needs to be added.
      placeholder: ship me!
    validations:
      required: true
